import {useState,useEffect,useRef} from "react";
import {createClient} from "@supabase/supabase-js";
const supa=createClient("https://unzohyrabvouclsjcpfu.supabase.co","sb_publishable_zB3k0KebVFw4-xf_TtdaUw_UlHsXk_q");
const ADMIN="nicholasu9@gmail.com";
const PAYSTACK_PK="pk_test_aaa1ae824c287d9865dd27a044670676c0df836d";
const LOGO="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ccircle cx='50' cy='50' r='48' fill='%230A1931'/%3E%3Cpath d='M30 28 L45 28 L42 42 L32 50 L18 38 Z M55 42 L62 48 L38 78 L30 78 L22 70 L30 62 L40 62 L55 42 Z M70 22 C78 22 86 28 86 38 C86 44 83 48 78 50 L62 56 L58 40 L64 36 C62 32 64 26 70 22 Z' fill='%23FFD700'/%3E%3C/svg%3E";

export default function App(){
const [tab,setTab]=useState("home");
const [user,setUser]=useState(JSON.parse(localStorage.getItem("cs_user")||"null"));
const [email,setEmail]=useState("");const [pass,setPass]=useState("");
const [jobs,setJobs]=useState([]);const [arts,setArts]=useState([]);const [msgs,setMsgs]=useState([]);const [pays,setPays]=useState([]);const [hires,setHires]=useState([]);const [ads,setAds]=useState([]);
const [jt,setJt]=useState("");const [jl,setJl]=useState("");const [jb,setJb]=useState("");const [jd,setJd]=useState("");const [ji,setJi]=useState("");const [pv,setPv]=useState(null);
const [an,setAn]=useState("");const [askill,setAskill]=useState("");const [aloc,setAloc]=useState("");const [awhat,setAwhat]=useState("");const [aport,setAport]=useState("");const [abio,setAbio]=useState("");const [aworks,setAworks]=useState([]);
const [chatJob,setChatJob]=useState(null);const [chatTxt,setChatTxt]=useState("");const [payModal,setPayModal]=useState(null);
const [searchSkill,setSearchSkill]=useState("");const [searchLoc,setSearchLoc]=useState("");const [selectedArt,setSelectedArt]=useState(null);
const [adCompany,setAdCompany]=useState("");const [adTitle,setAdTitle]=useState("");const [adImg,setAdImg]=useState("");const [adLink,setAdLink]=useState("");const [adPackage,setAdPackage]=useState("Basic");
// NEW VERIFICATION
const [otpSent,setOtpSent]=useState("");const [otpInput,setOtpInput]=useState("");const [phoneVerified,setPhoneVerified]=useState(false);const [verEmail,setVerEmail]=useState("");
const chatEndRef=useRef(null);

const load=async()=>{
const {data:j}=await supa.from("jobs").select("*").order("id",{ascending:false}).limit(20);if(j)setJobs(j);
const {data:a}=await supa.from("artisans").select("*").order("id",{ascending:false}).limit(30);if(a)setArts(a);
const {data:m}=await supa.from("messages").select("*").order("id",{ascending:true}).limit(100);if(m)setMsgs(m);
const {data:p}=await supa.from("payments").select("*").order("id",{ascending:false}).limit(30);if(p)setPays(p);
const {data:h}=await supa.from("hires").select("*").order("id",{ascending:false}).limit(30);if(h)setHires(h);
const {data:ad}=await supa.from("ads").select("*").order("id",{ascending:false}).limit(8);if(ad)setAds(ad);
};
useEffect(()=>{load();},[]);
useEffect(()=>{if(chatEndRef.current)chatEndRef.current.scrollIntoView({behavior:"smooth"});},[msgs,chatJob]);
useEffect(()=>{const s=document.createElement("script");s.src="https://js.paystack.co/v1/inline.js";s.async=true;document.body.appendChild(s);return()=>{try{document.body.removeChild(s);}catch(e){}};},[]);

const signup=async()=>{const {error}=await supa.auth.signUp({email,password:pass});if(error)return alert(error.message);const u={email,role:email===ADMIN?"admin":"user"};localStorage.setItem("cs_user",JSON.stringify(u));setUser(u);setTab("home");};
const login=async()=>{const {error}=await supa.auth.signInWithPassword({email,password:pass});if(error)return alert(error.message);const u={email,role:email===ADMIN?"admin":"user"};localStorage.setItem("cs_user",JSON.stringify(u));setUser(u);setTab("home");};
const compress=(b64,maxW,q)=>{return new Promise(r=>{const i=new Image();i.onload=()=>{const c=document.createElement("canvas");let w=i.width,h=i.height;if(w>maxW){h=h*maxW/w;w=maxW;}c.width=w;c.height=h;c.getContext("2d").drawImage(i,0,0,w,h);r(c.toDataURL("image/jpeg",q));};i.src=b64;});};
const up=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{compress(ev.target.result,600,0.4).then(c=>setJi(c));};r.readAsDataURL(f);};
const upArt=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{compress(ev.target.result,300,0.4).then(c=>setAport(c));};r.readAsDataURL(f);};
const upWorks=e=>{const files=Array.from(e.target.files).slice(0,5);files.forEach(f=>{const r=new FileReader();r.onload=ev=>{compress(ev.target.result,500,0.4).then(c=>setAworks(p=>[...p,c].slice(0,5)));};r.readAsDataURL(f);});};
const upAd=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{compress(ev.target.result,500,0.5).then(c=>setAdImg(c));};r.readAsDataURL(f);};

// VERIFICATION FUNCTIONS
const sendOtp=()=>{if(awhat.length<10)return alert("Enter valid phone e.g. 080... or +233...");const code=Math.floor(100000+Math.random()*900000).toString();setOtpSent(code);alert("Your CraftSure NG verification code is: "+code+" (Demo - In production will SMS)");};
const verifyOtp=()=>{if(otpInput===otpSent){setPhoneVerified(true);alert("Phone verified! ✅");}else alert("Wrong code");};
const sendEmailOtp=()=>{if(!verEmail.includes("@"))return alert("Enter valid email");setOtpSent("123456");alert("Email code sent to "+verEmail+": 123456 (Demo)");};

const postJob=async()=>{if(!user)return alert("Login first! Go to Login tab");await supa.from("jobs").insert([{title:jt,location:jl,budget:jb,description:jd,image_url:ji,created_by:user.email}]);setJt("");setJl("");setJb("");setJd("");setJi("");load();setTab("home");};
const postArt=async()=>{
if(!an||!askill||!aloc||!awhat)return alert("Fill name, skill, location, phone");
if(!aport)return alert("Upload profile photo - Required!");
if(!phoneVerified)return alert("Verify phone number first! Click Send OTP");
if(!verEmail)return alert("Enter verification email");
if(aworks.length===0)return alert("Upload at least 1 Jobs Done photo");
const worksJson=JSON.stringify(aworks);
const {error}=await supa.from("artisans").insert([{name:an,skill:askill,location:aloc,whatsapp:awhat,portfolio:aport,bio:abio||"Verified by CraftSure NG",works:worksJson,rating:4.9,jobs_done:aworks.length,created_by:verEmail||user?.email||"guest@craftsureng.com",verified:true,phone_verified:phoneVerified}]);
if(error){alert("Error: "+error.message);return;}
alert("✅ Account opened! "+an+" verified with "+aworks.length+" photos!");setAworks([]);setAn("");setAskill("");setAloc("");setAwhat("");setAport("");setAbio("");setPhoneVerified(false);setOtpSent("");load();setTab("artisans");
};
const postAd=async()=>{if(!user)return alert("Login");const amt=adPackage==="Basic"?20000:adPackage==="Premium"?50000:100000;await supa.from("ads").insert([{company_name:adCompany,title:adTitle,image_url:adImg,link:adLink,package:adPackage,amount:amt,created_by:user.email,status:"active"}]);setAdCompany("");setAdTitle("");setAdImg("");setAdLink("");load();setTab("home");};
const delJob=async(id)=>{if(!confirm("Delete?"))return;await supa.from("jobs").delete().eq("id",id);load();};
const delAd=async(id)=>{if(!confirm("Delete ad?"))return;await supa.from("ads").delete().eq("id",id);load();};
const hireArtisan=async(em,name,jid)=>{const id=jid||(chatJob&&chatJob.id)||(jobs[0]&&jobs[0].id);if(!id)return alert("Select job");await supa.from("hires").insert([{job_id:id,client_email:user.email,artisan_email:em,artisan_name:name,status:"hired"}]);alert("Hired "+name+"!");load();setSelectedArt(null);};
const sendMsg=async()=>{if(!chatTxt.trim()||!chatJob)return;await supa.from("messages").insert([{job_id:chatJob.id,sender:user.email,receiver:"all",message:chatTxt}]);setChatTxt("");load();};
const getBudget=(b)=>{let n=parseInt((b||"").replace(/[^0-9]/g,""))||0;if((b||"").toLowerCase().includes("k"))n=n*1000;return n;};
const hasPaid=(id,t)=>pays.some(p=>p.job_id===id&&p.percent_type===t);
const isHired=(id)=>hires.find(h=>h.job_id===id);
const openPay=(job,type)=>{const b=getBudget(job.budget);const fee=type==="client"?Math.floor(b*0.05):Math.floor(b*0.10);const total=type==="client"?b+fee:fee;setPayModal({job,type,budget:b,fee,total});};
const payWithPaystack=()=>{if(!payModal||!window.PaystackPop)return;const kobo=payModal.type==="client"?payModal.total*100:payModal.fee*100;const h=window.PaystackPop.setup({key:PAYSTACK_PK,email:user.email,amount:kobo,currency:"NGN",ref:"CS_"+Math.floor(Math.random()*1000000000),callback:async(r)=>{await supa.from("payments").insert([{job_id:payModal.job.id,payer_email:user.email,payer_type:payModal.type,amount:payModal.fee,percent_type:payModal.type==="client"?"5%_client":"10%_artisan",status:"paid"}]);setPayModal(null);alert("Paid! Ref: "+r.reference);load();},onClose:()=>{}});h.openIframe();};
const filteredArts=arts.filter(a=>{const sOk=!searchSkill||a.skill.toLowerCase().includes(searchSkill.toLowerCase())||a.name.toLowerCase().includes(searchSkill.toLowerCase());const lOk=!searchLoc||a.location.toLowerCase().includes(searchLoc.toLowerCase());return sOk&&lOk;});
const client5Total=pays.filter(p=>p.percent_type==="5%_client").reduce((s,p)=>s+p.amount,0);
const artisan10Total=pays.filter(p=>p.percent_type==="10%_artisan").reduce((s,p)=>s+p.amount,0);
const adTotal=ads.reduce((s,a)=>s+(a.amount||0),0);
const grand=client5Total+artisan10Total+adTotal;
const isAdmin=user&&user.email===ADMIN;
const parseWorks=(w)=>{try{const a=JSON.parse(w||"[]");return Array.isArray(a)?a:[];}catch(e){return [];}};

return(
<div style={{background:"#f5f7fb",minHeight:"100vh",fontFamily:"sans-serif"}}>
<div style={{background:"#0A1931",color:"#fff",padding:"10px 14px",display:"flex",justifyContent:"space-between",alignItems:"center",position:"sticky",top:0,zIndex:20,borderBottom:"3px solid #FFD700"}}>
<div style={{display:"flex",alignItems:"center",gap:"9px"}}><img src={LOGO} style={{width:38,height:38,borderRadius:"50%",background:"#fff",padding:"2px",border:"2px solid #FFD700"}} alt="logo"/><div><b style={{fontSize:16}}>CraftSure NG 🇳🇬🇬🇭</b><div style={{fontSize:8,color:"#FFD700",fontWeight:"bold"}}>NIGERIA & GHANA • VERIFIED</div></div></div>
<div style={{display:"flex",gap:"5px",flexWrap:"wrap"}}>
<button onClick={()=>setTab("home")} style={{padding:"7px 12px",borderRadius:8,border:"none",background:tab==="home"?"#fff":"#112240",color:tab==="home"?"#0A1931":"#fff",fontSize:11,fontWeight:"600"}}>Home</button>
<button onClick={()=>setTab("artisans")} style={{padding:"7px 12px",borderRadius:8,border:"none",background:tab==="artisans"?"#fff":"#112240",color:tab==="artisans"?"#0A1931":"#fff",fontSize:11,fontWeight:"600"}}>Artisans</button>
<button onClick={()=>setTab("brands")} style={{padding:"7px 12px",borderRadius:8,border:"none",background:tab==="brands"?"#FFD700":"#112240",color:tab==="brands"?"#0A1931":"#fff",fontSize:11,fontWeight:"bold"}}>Ads</button>
{isAdmin&&<button onClick={()=>setTab("admin")} style={{padding:"7px 12px",borderRadius:8,border:"none",background:"#ef4444",color:"#fff",fontSize:11,fontWeight:"bold"}}>Admin</button>}
<button onClick={()=>setTab("post")} style={{padding:"7px 12px",borderRadius:8,border:"none",background:"#FFD700",color:"#0A1931",fontWeight:"bold",fontSize:11}}>Post Job</button>
<button onClick={()=>setTab("join")} style={{padding:"7px 12px",borderRadius:8,border:"none",background:"#22c55e",color:"#fff",fontWeight:"bold",fontSize:11}}>+ Join</button>
{user?<button onClick={()=>{localStorage.removeItem("cs_user");setUser(null);}} style={{padding:"6px 9px",borderRadius:8,border:"1px solid #FFD700",background:"#fff",fontSize:10}}>{user.email.slice(0,5)} Out</button>:<button onClick={()=>setTab("login")} style={{padding:"7px 12px",borderRadius:8,border:"none",background:"#fff",color:"#0A1931",fontWeight:"bold",fontSize:11}}>Login</button>}
</div>
</div>
<div style={{background:"#e6f4ea",padding:"7px 14px",display:"flex",justifyContent:"space-between"}}><small style={{fontSize:10,color:"#155724",fontWeight:"600"}}>🇳🇬🇬🇭 Data Saver • Verified • Paystack & MoMo</small><button onClick={load} style={{padding:"5px 12px",borderRadius:20,border:"none",background:"#0A1931",color:"#FFD700",fontSize:10,fontWeight:"bold"}}>Refresh</button></div>
{tab==="home"&&<div>{ads.length>0&&<div style={{background:"#0A1931",padding:"10px"}}><div style={{display:"flex",gap:"8px",overflowX:"auto"}}>{ads.map(ad=><div key={ad.id} onClick={()=>window.open(ad.link,"_blank")} style={{minWidth:"270px",background:"#fff",borderRadius:12,overflow:"hidden",display:"flex",cursor:"pointer",border:"2px solid #FFD700"}}><img loading="lazy" src={ad.image_url} style={{width:64,height:64,objectFit:"cover"}} alt="ad"/><div style={{padding:"7px",flex:1}}><small style={{background:"#FFD700",color:"#0A1931",padding:"2px 6px",borderRadius:10,fontSize:7,fontWeight:"bold"}}>SPONSORED</small><br/><b style={{fontSize:11,color:"#0A1931"}}>{ad.company_name}</b><br/><small style={{fontSize:9}}>{ad.title}</small></div></div>)}</div></div>}<div style={{padding:"12px 16px",background:"#fff"}}><b style={{color:"#0A1931"}}>Jobs ({jobs.length}) 🇳🇬🇬🇭</b></div>{jobs.map(j=>{const b=getBudget(j.budget);const hired=isHired(j.id);return(<div key={j.id} style={{background:"#fff",margin:"12px 16px",borderRadius:14,overflow:"hidden",border:"1px solid #e5e7eb"}}>{j.image_url&&<div style={{position:"relative"}} onClick={()=>setPv(j.image_url)}><img loading="lazy" src={j.image_url} style={{width:"100%",height:170,objectFit:"cover"}} alt="job"/><div style={{position:"absolute",top:10,right:10,display:"flex",gap:"6px"}}>{hired&&<span style={{background:"#0A1931",color:"#FFD700",padding:"5px 10px",borderRadius:20,fontSize:9,fontWeight:"bold"}}>Hired: {hired.artisan_name}</span>}{user&&user.email===j.created_by&&<button onClick={(e)=>{e.stopPropagation();delJob(j.id);}} style={{background:"#fee2e2",color:"#ef4444",border:"none",borderRadius:"50%",width:28,height:28}}>X</button>}</div></div>}<div style={{padding:"12px"}}><b style={{fontSize:13,color:"#0A1931"}}>{j.title}</b><br/><small style={{color:"#666",fontSize:11}}>📍 {j.location} • 💰 ₦{b.toLocaleString()} / GH₵</small><br/><small style={{color:"#555",fontSize:11}}>{j.description}</small><div style={{display:"flex",gap:8,marginTop:12}}><button onClick={()=>{if(!user)return alert("Login");setChatJob(j);}} style={{flex:1,padding:"10px",border:"none",borderRadius:10,background:"#0A1931",color:"#FFD700",fontWeight:"bold",fontSize:11}}>Chat to Hire</button>{!hasPaid(j.id,"5%_client")&&<button onClick={()=>openPay(j,"client")} style={{flex:1,padding:"10px",border:"none",borderRadius:10,background:"#FFD700",color:"#0A1931",fontWeight:"bold",fontSize:11}}>Unlock</button>}</div></div></div>);})}</div>}
{tab==="artisans"&&<div style={{padding:"14px"}}><div style={{background:"#fff",padding:"14px",borderRadius:14,marginBottom:"12px",border:"1px solid #e5e7eb"}}><b style={{color:"#0A1931"}}>Artisans NG & GH • Verified Portfolio 🇳🇬🇬🇭</b><div style={{display:"flex",gap:8,marginTop:"10px"}}><input value={searchSkill} onChange={e=>setSearchSkill(e.target.value)} placeholder="Search skill" style={{flex:1,padding:"10px",borderRadius:10,border:"1px solid #ddd",fontSize:12}}/><input value={searchLoc} onChange={e=>setSearchLoc(e.target.value)} placeholder="Lagos, Accra..." style={{flex:1,padding:"10px",borderRadius:10,border:"1px solid #ddd",fontSize:12}}/></div></div>{filteredArts.map(a=>{const works=parseWorks(a.works);return(<div key={a.id} onClick={()=>setSelectedArt(a)} style={{background:"#fff",padding:"12px",borderRadius:14,marginBottom:"10px",display:"flex",gap:"12px",border:"1px solid #e5e7eb",cursor:"pointer"}}>{a.portfolio&&<img loading="lazy" src={a.portfolio} style={{width:62,height:62,borderRadius:14,objectFit:"cover",border:"2px solid #FFD700"}} alt="port"/>}<div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:6}}><b style={{fontSize:12,color:"#0A1931"}}>{a.name}</b><small style={{background:"#0A1931",color:"#FFD700",padding:"3px 7px",borderRadius:10,fontSize:8,fontWeight:"bold"}}>{a.skill}</small>{a.phone_verified&&<small style={{background:"#22c55e",color:"#fff",padding:"2px 5px",borderRadius:10,fontSize:7}}>✓ Phone</small>}</div><small style={{fontSize:10,color:"#666"}}>📍 {a.location} • {works.length} jobs</small></div><button style={{padding:"7px 12px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:10,fontSize:10,height:"32px",fontWeight:"bold"}}>View</button></div>);})}</div>}
{tab==="join"&&<div style={{padding:"14px"}}><h3 style={{color:"#0A1931"}}>Join as Artisan — CraftSure NG 🇳🇬🇬🇭</h3><div style={{background:"#fff",padding:"14px",borderRadius:14,border:"1px solid #e5e7eb"}}><input value={an} onChange={e=>setAn(e.target.value)} placeholder="Full Name *" style={{width:"100%",padding:"11px",marginBottom:"9px",borderRadius:10,border:"1px solid #ddd"}}/><input value={askill} onChange={e=>setAskill(e.target.value)} placeholder="Skill e.g. Tiler, Barber *" style={{width:"100%",padding:"11px",marginBottom:"9px",borderRadius:10,border:"1px solid #ddd"}}/><input value={aloc} onChange={e=>setAloc(e.target.value)} placeholder="Location e.g. Lagos, Accra *" style={{width:"100%",padding:"11px",marginBottom:"9px",borderRadius:10,border:"1px solid #ddd"}}/>
<div style={{background:"#f0f9ff",padding:"10px",borderRadius:10,marginBottom:"9px",border:"1px solid #0A1931"}}><b style={{fontSize:11,color:"#0A1931"}}>📱 Phone Verification * (Nigeria & Ghana)</b><div style={{display:"flex",gap:"6px",marginTop:"6px"}}><input value={awhat} onChange={e=>setAwhat(e.target.value)} placeholder="080... or +233..." style={{flex:1,padding:"10px",borderRadius:8,border:"1px solid #ddd"}}/><button onClick={sendOtp} style={{padding:"10px 12px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:8,fontSize:10,fontWeight:"bold"}}>Send OTP</button></div><div style={{display:"flex",gap:"6px",marginTop:"6px"}}><input value={otpInput} onChange={e=>setOtpInput(e.target.value)} placeholder="Enter 6-digit code" style={{flex:1,padding:"10px",borderRadius:8,border:"1px solid #ddd"}}/><button onClick={verifyOtp} style={{padding:"10px 12px",background:phoneVerified?"#22c55e":"#FFD700",color:phoneVerified?"#fff":"#0A1931",border:"none",borderRadius:8,fontSize:10,fontWeight:"bold"}}>{phoneVerified?"Verified ✅":"Verify"}</button></div>{phoneVerified&&<small style={{color:"#22c55e",fontSize:10}}>✅ Phone verified - Secure!</small>}</div>
<div style={{background:"#fff8e6",padding:"10px",borderRadius:10,marginBottom:"9px",border:"1px solid #FFD700"}}><b style={{fontSize:11,color:"#0A1931"}}>📧 Email Verification *</b><input value={verEmail} onChange={e=>setVerEmail(e.target.value)} placeholder="your@email.com" style={{width:"100%",padding:"10px",marginTop:"6px",borderRadius:8,border:"1px solid #ddd"}}/><small style={{fontSize:9,color:"#666"}}>We will verify this email for security. Must match your login email if logged in.</small></div>
<div><b style={{fontSize:11,color:"#0A1931"}}>Profile Photo * (30KB auto compressed)</b><input type="file" accept="image/*" onChange={upArt} style={{marginTop:"6px",marginBottom:"8px"}}/>{aport&&<img src={aport} style={{width:64,height:64,borderRadius:"50%",border:"3px solid #FFD700",objectFit:"cover"}} alt="port"/>}</div><div style={{marginTop:"12px",background:"#f8f9ff",padding:"10px",borderRadius:12,border:"1px dashed #0A1931"}}><b style={{fontSize:11,color:"#0A1931"}}>📸 Jobs Done - Max 5 - Instagram Style *</b><small style={{display:"block",fontSize:9,color:"#666"}}>Upload clear photos of your work - Auto compressed to 30KB each!</small><input type="file" accept="image/*" multiple onChange={upWorks} style={{marginTop:"6px"}}/><div style={{display:"flex",gap:"6px",flexWrap:"wrap",marginTop:"8px"}}>{aworks.map((w,i)=><div key={i} style={{position:"relative"}}><img src={w} style={{width:52,height:52,borderRadius:10,objectFit:"cover",border:"2px solid #FFD700"}} alt="work"/><button onClick={()=>setAworks(aworks.filter((_,idx)=>idx!==i))} style={{position:"absolute",top:-6,right:-6,background:"#ef4444",color:"#fff",border:"none",borderRadius:"50%",width:16,height:16,fontSize:9}}>X</button></div>)}</div>{aworks.length>0&&<small style={{color:"#22c55e",fontSize:10}}>✅ {aworks.length} photos ready - Compressed!</small>}</div><input value={abio} onChange={e=>setAbio(e.target.value)} placeholder="Bio e.g. 10 years experience in Lagos & Accra" style={{width:"100%",padding:"11px",marginTop:"10px",borderRadius:10,border:"1px solid #ddd"}}/><button onClick={postArt} style={{width:"100%",marginTop:"14px",padding:"13px",background:phoneVerified?"#0A1931":"#999",color:"#FFD700",border:"none",borderRadius:12,fontWeight:"bold"}}>{phoneVerified?`Create Verified Portfolio • ${aworks.length} photos`:"Verify Phone to Create Account"}</button><small style={{display:"block",textAlign:"center",marginTop:"6px",fontSize:9,color:"#666"}}>🔒 Secure - Phone & Email verified - Escrow protected</small></div></div>}
{tab==="post"&&<div style={{padding:"14px"}}><h3 style={{color:"#0A1931"}}>Post a Job — NG & GH</h3><div style={{background:"#fff",padding:"14px",borderRadius:14,border:"1px solid #e5e7eb"}}><input value={jt} onChange={e=>setJt(e.target.value)} placeholder="Job Title" style={{width:"100%",padding:"11px",marginBottom:"9px",borderRadius:10,border:"1px solid #ddd"}}/><input value={jl} onChange={e=>setJl(e.target.value)} placeholder="Location e.g. Lekki, East Legon" style={{width:"100%",padding:"11px",marginBottom:"9px",borderRadius:10,border:"1px solid #ddd"}}/><input value={jb} onChange={e=>setJb(e.target.value)} placeholder="Budget e.g. 80000 or GH₵500" style={{width:"100%",padding:"11px",marginBottom:"9px",borderRadius:10,border:"1px solid #ddd"}}/><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Description" style={{width:"100%",padding:"11px",marginBottom:"9px",borderRadius:10,border:"1px solid #ddd",height:"70px"}}/><input type="file" accept="image/*" onChange={up} style={{marginBottom:"8px"}}/>{ji&&<img src={ji} style={{width:"100%",maxHeight:"160px",borderRadius:12,marginBottom:"8px"}} alt="prev"/>}<button onClick={postJob} style={{width:"100%",padding:"13px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:12,fontWeight:"bold"}}>Post Job — Nigeria & Ghana</button></div></div>}
{tab==="brands"&&<div style={{padding:"14px"}}><h3 style={{color:"#0A1931"}}>Advertise — NG & GH Brands 🇳🇬🇬🇭</h3><div style={{background:"#fff",padding:"14px",borderRadius:14,marginTop:"12px",border:"1px solid #e5e7eb"}}><b style={{color:"#0A1931"}}>Post Ad</b><input value={adCompany} onChange={e=>setAdCompany(e.target.value)} placeholder="Company Name" style={{width:"100%",padding:"11px",marginTop:"9px",borderRadius:10,border:"1px solid #ddd"}}/><input value={adTitle} onChange={e=>setAdTitle(e.target.value)} placeholder="Ad Title" style={{width:"100%",padding:"11px",marginTop:"9px",borderRadius:10,border:"1px solid #ddd"}}/><input value={adLink} onChange={e=>setAdLink(e.target.value)} placeholder="Link" style={{width:"100%",padding:"11px",marginTop:"9px",borderRadius:10,border:"1px solid #ddd"}}/><select value={adPackage} onChange={e=>setAdPackage(e.target.value)} style={{width:"100%",padding:"11px",marginTop:"9px",borderRadius:10,border:"1px solid #ddd"}}><option>Basic - ₦20k / GH₵200</option><option>Premium - ₦50k / GH₵500</option><option>Gold - ₦100k / GH₵1000</option></select><input type="file" accept="image/*" onChange={upAd} style={{marginTop:"8px"}}/>{adImg&&<img src={adImg} style={{width:"100%",maxHeight:"150px",borderRadius:12,marginTop:"8px"}} alt="ad"/>}<button onClick={postAd} style={{width:"100%",marginTop:"12px",padding:"13px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:12,fontWeight:"bold"}}>Post Ad</button></div></div>}
{tab==="login"&&<div style={{padding:"24px",display:"flex",justifyContent:"center"}}><div style={{background:"#fff",padding:"18px",borderRadius:16,width:"100%",maxWidth:"360px",border:"2px solid #0A1931"}}><b style={{color:"#0A1931"}}>Login — CraftSure NG 🇳🇬🇬🇭</b><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email (verified)" style={{width:"100%",padding:"11px",marginTop:"12px",borderRadius:10,border:"1px solid #ddd"}}/><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Password" style={{width:"100%",padding:"11px",marginTop:"9px",borderRadius:10,border:"1px solid #ddd"}}/><button onClick={login} style={{width:"100%",padding:"12px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:10,fontWeight:"bold",marginTop:"12px"}}>Login Secure</button><button onClick={signup} style={{width:"100%",padding:"12px",background:"#fff",color:"#0A1931",border:"1.5px solid #0A1931",borderRadius:10,fontWeight:"bold",marginTop:"9px"}}>Create Verified Account</button><small style={{display:"block",marginTop:"8px",fontSize:9,color:"#666",textAlign:"center"}}>🔒 Email verified accounts only. Phone OTP required for artisans.</small></div></div>}
{tab==="admin"&&isAdmin&&<div style={{padding:"14px"}}><h2 style={{color:"#0A1931"}}>Admin — NG & GH Revenue</h2><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"10px",marginTop:"12px"}}><div style={{background:"#0A1931",color:"#fff",padding:"14px",borderRadius:14,border:"1px solid #FFD700"}}><small style={{color:"#FFD700"}}>Jobs NG/GH</small><h2 style={{color:"#FFD700"}}>{jobs.length}</h2></div><div style={{background:"#fff",padding:"14px",borderRadius:14,border:"1px solid #e5e7eb"}}><small>Artisans Verified</small><h2 style={{color:"#0A1931"}}>{arts.filter(a=>a.phone_verified).length}/{arts.length}</h2></div><div style={{background:"#FFD700",color:"#0A1931",padding:"14px",borderRadius:14}}><small>Client 5%</small><h2>₦{client5Total.toLocaleString()}</h2></div><div style={{background:"#112240",color:"#fff",padding:"14px",borderRadius:14}}><small style={{color:"#FFD700"}}>Artisan 10%</small><h2>₦{artisan10Total.toLocaleString()}</h2></div><div style={{background:"#0A1931",color:"#fff",padding:"14px",borderRadius:14,border:"2px solid #FFD700"}}><small style={{color:"#FFD700"}}>GRAND</small><h2 style={{color:"#FFD700"}}>₦{grand.toLocaleString()}</h2></div></div></div>}
{selectedArt&&<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"#fff",zIndex:70,overflowY:"auto"}}><div style={{background:"#0A1931",color:"#fff",padding:"12px",display:"flex",justifyContent:"space-between",alignItems:"center",position:"sticky",top:0,borderBottom:"3px solid #FFD700"}}><div style={{display:"flex",alignItems:"center",gap:"10px"}}><img src={selectedArt.portfolio} style={{width:42,height:42,borderRadius:"50%",border:"2px solid #FFD700",objectFit:"cover"}} alt="art"/><div><b style={{color:"#FFD700"}}>{selectedArt.name}</b><div style={{fontSize:10,color:"#ccc"}}>{selectedArt.skill} • {selectedArt.location} {selectedArt.phone_verified?"✅":""}</div></div></div><button onClick={()=>setSelectedArt(null)} style={{background:"#fff",border:"none",borderRadius:"50%",width:32,height:32,fontWeight:"bold"}}>X</button></div><div style={{padding:"14px"}}><img loading="lazy" src={selectedArt.portfolio} style={{width:"100%",height:240,objectFit:"cover",borderRadius:14,border:"3px solid #FFD700"}} alt="portfolio"/><div style={{display:"flex",gap:6,marginTop:"12px",flexWrap:"wrap"}}><span style={{background:"#0A1931",color:"#FFD700",padding:"5px 10px",borderRadius:20,fontSize:10,fontWeight:"bold"}}>✓ Verified</span>{selectedArt.phone_verified&&<span style={{background:"#22c55e",color:"#fff",padding:"5px 10px",borderRadius:20,fontSize:10,fontWeight:"bold"}}>✓ Phone Verified</span>}<span style={{background:"#FFD700",color:"#0A1931",padding:"5px 10px",borderRadius:20,fontSize:10,fontWeight:"bold"}}>★ {selectedArt.rating||5.0}</span></div><div style={{background:"#f8f9ff",padding:"12px",borderRadius:12,marginTop:"12px",border:"1px solid #eef0ff"}}><b style={{fontSize:12,color:"#0A1931"}}>About — NG & GH</b><p style={{fontSize:12,marginTop:"4px",color:"#555"}}>{selectedArt.bio}</p></div><div style={{marginTop:"14px"}}><b style={{color:"#0A1931"}}>Jobs Done ({parseWorks(selectedArt.works).length})</b><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"8px",marginTop:"8px"}}>{parseWorks(selectedArt.works).map((w,i)=><img key={i} loading="lazy" src={w} onClick={()=>setPv(w)} style={{width:"100%",height:95,objectFit:"cover",borderRadius:12,border:"2px solid #FFD700",cursor:"pointer"}} alt="work"/>)}</div></div><div style={{display:"flex",gap:"8px",marginTop:"16px"}}><button onClick={()=>{if(jobs.length>0){setChatJob(jobs[0]);setSelectedArt(null);}}} style={{flex:1,padding:"13px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:12,fontWeight:"bold"}}>Chat</button><button onClick={()=>hireArtisan(selectedArt.created_by,selectedArt.name)} style={{flex:1,padding:"13px",background:"#FFD700",color:"#0A1931",border:"none",borderRadius:12,fontWeight:"bold"}}>Hire Now — Verified</button></div></div></div>}
{chatJob&&<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"#f5f7fb",zIndex:50,display:"flex",flexDirection:"column"}}><div style={{background:"#0A1931",color:"#fff",padding:"12px",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"3px solid #FFD700"}}><div><b style={{color:"#FFD700"}}>Chat: {chatJob.title}</b><div style={{fontSize:10,color:"#ccc"}}>Secure • Verified • NG & GH</div></div><button onClick={()=>setChatJob(null)} style={{background:"#fff",border:"none",borderRadius:"50%",width:32,height:32,fontWeight:"bold"}}>X</button></div><div style={{flex:1,overflowY:"auto",padding:"12px"}}>{msgs.filter(m=>m.job_id===chatJob.id).map(m=><div key={m.id} style={{background:m.sender===user.email?"#0A1931":"#fff",color:m.sender===user.email?"#FFD700":"#111",padding:"9px 12px",borderRadius:14,margin:"7px 0",maxWidth:"84%",marginLeft:m.sender===user.email?"auto":"0",fontSize:12,border:"1px solid #e5e7eb"}}>{m.message}</div>)}<div ref={chatEndRef}></div></div><div style={{padding:"12px",background:"#fff",display:"flex",gap:"8px",borderTop:"1px solid #e5e7eb"}}><input value={chatTxt} onChange={e=>setChatTxt(e.target.value)} placeholder="Negotiate..." style={{flex:1,padding:"12px",borderRadius:24,border:"1px solid #ddd"}}/><button onClick={sendMsg} style={{padding:"11px 18px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:24,fontWeight:"bold"}}>Send</button></div></div>}
{payModal&&<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(10,25,49,0.65)",zIndex:60,display:"flex",alignItems:"center",justifyContent:"center",padding:"16px"}}><div style={{background:"#fff",borderRadius:16,width:"100%",maxWidth:"360px",overflow:"hidden",border:"2px solid #0A1931"}}><div style={{background:"#0A1931",color:"#fff",padding:"14px",borderBottom:"3px solid #FFD700"}}><b style={{color:"#FFD700"}}>Secure — Paystack & MoMo 🇳🇬🇬🇭</b></div><div style={{padding:"16px"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"8px"}}><span>Budget</span><b>₦{payModal.budget.toLocaleString()}</b></div><div style={{display:"flex",justifyContent:"space-between",marginBottom:"8px",color:"#666",fontSize:12}}><span>Fee ({payModal.type==="client"?"5%":"10%"})</span><span>₦{payModal.fee.toLocaleString()}</span></div><div style={{borderTop:"1px dashed #ddd",margin:"10px 0"}}></div><div style={{display:"flex",justifyContent:"space-between",fontWeight:"bold",fontSize:16,color:"#0A1931"}}><span>Total</span><span>₦{payModal.type==="client"?payModal.total.toLocaleString():payModal.fee.toLocaleString()}</span></div><button onClick={payWithPaystack} style={{width:"100%",marginTop:"14px",padding:"13px",background:"#0A1931",color:"#FFD700",border:"none",borderRadius:12,fontWeight:"bold"}}>Pay with Paystack / MoMo</button><button onClick={()=>setPayModal(null)} style={{width:"100%",marginTop:"9px",padding:"11px",background:"#fff",color:"#0A1931",border:"1px solid #ddd",borderRadius:12}}>Cancel</button></div></div></div>}
{pv&&<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.96)",zIndex:100,display:"flex",flexDirection:"column"}}><div style={{display:"flex",justifyContent:"space-between",padding:"12px",color:"#fff"}}><b style={{color:"#FFD700"}}>Protected — NG & GH</b><button onClick={()=>setPv(null)} style={{background:"#fff",border:"none",borderRadius:"50%",width:32,height:32,fontWeight:"bold"}}>X</button></div><div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center"}}><img src={pv} style={{maxWidth:"95%",maxHeight:"80vh",borderRadius:12,border:"3px solid #FFD700"}} alt="full"/></div></div>}
</div>
)
}
